# Generated by Django 5.2.4 on 2025-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='affected',
            field=models.TextField(default='Not specified', max_length=255),
        ),
    ]
