# Generated by Django 5.2.3 on 2026-07-03 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_findingcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accept_until', models.DateField()),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_acceptances', to='findings.finding')),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
    ]
