# Generated by Django 5.2.3 on 2026-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanreport',
            name='source_tool',
            field=models.CharField(choices=[('burp', 'Burp Suite'), ('zap', 'OWASP ZAP'), ('nessus', 'Nessus'), ('acunetix', 'Acunetix'), ('nmap', 'Nmap'), ('openvas', 'OpenVAS CSV'), ('csv', 'Generic CSV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
