# Generated by Django 5.2.4 on 2025-07-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_completed_date_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], max_length=10)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('done', 'Done')], default='loading', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
        ),
    ]
