# Generated by Django 5.2.3 on 2026-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='status',
            field=models.CharField(choices=[('loading', 'Loading'), ('done', 'Done'), ('failed', 'Failed')], default='loading', max_length=10),
        ),
    ]
