# Generated by Django 5.2.3 on 2026-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reporthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('md', 'Markdown')], max_length=10),
        ),
    ]
