# Generated by Django 5.2.3 on 2026-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reporthistory_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='format',
            field=models.CharField(choices=[('md', 'Markdown')], max_length=10),
        ),
    ]
