# Generated by Django 5.2.3 on 2026-07-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reporthistory_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Report Template',
            },
        ),
    ]
