# Generated by Django 5.2.3 on 2025-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, unique=True)),
                ('menu_url', models.URLField(max_length=255, unique=True)),
            ],
        ),
    ]
