# Generated by Django 5.2.3 on 2025-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
